[package]
authors = ["Chris Davison <c.jr.davison@gmail.com>"]
edition = "2018"
name = "bookmarks"
version = "0.2.0"
license = "MIT"
description = "Utility to manage plaintext bookmarks"

[dependencies]
tagsearch = "0.20.1"
chrono = { version = "0.4", features = ["serde"] }
dirs = "2.0"
